language: php

php:
  - 7.0
  - hhvm

before_script:
  - composer self-update
  - composer install --dev --no-interaction

script:
  - mkdir -p build/logs
  - phpunit -c phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls
